version: 1.4.{build}
image: Visual Studio 2019
configuration: Release
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
  - ps: nuget restore
build:
  project: Wow.sln
after_test:
  - ps: Copy-Item $env:APPDATA\Wow\Logs\*\*.txt .
  - msbuild Wow.Installer\Wow.Installer.wixproj /p:Configuration=Release /p:BuildProjectReferences=false /t:Build"
artifacts:
  - path: '*-*-*.txt'
    name: information
  - path: 'Output\Packages\Wow-*.zip'
    name: installer
  - path: 'Output\Packages\Wow.Plugin.*.nupkg'
    name: nuget_package
  - path: 'Output\Packages\Wow.*.*'
    name: installer
  - path: 'Output\Packages\Wow-*.*'
    name: installer
  - path: 'Output\Packages\RELEASES'
    name: installer
  - path: 'Wow.Installer\Everything*.exe'
    name: installer
  - path: 'Wow.Installer\python*.exe'
    name: installer
